{{- if .Values.restartCron.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: agent-restart
spec:
  schedule: "{{ .Values.restartCron.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: drd-vpc-agent
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  echo "Restarting celery components..."
                  kubectl rollout restart deployment drd-vpc-agent-celery-beat -n {{ .Release.Namespace }}
                  kubectl rollout restart deployment drd-vpc-agent-celery-worker -n {{ .Release.Namespace }}
          restartPolicy: OnFailure
{{- end }}
