"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import protos.base_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class AsanaAlertOpsConfiguration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IS_ENABLED_FIELD_NUMBER: builtins.int
    @property
    def is_enabled(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    def __init__(
        self,
        *,
        is_enabled: google.protobuf.wrappers_pb2.BoolValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["is_enabled", b"is_enabled"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["is_enabled", b"is_enabled"]) -> None: ...

global___AsanaAlertOpsConfiguration = AsanaAlertOpsConfiguration

@typing_extensions.final
class AsanaProjectAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Workspace(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        WORKSPACE_ID_FIELD_NUMBER: builtins.int
        WORKSPACE_NAME_FIELD_NUMBER: builtins.int
        @property
        def workspace_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def workspace_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            workspace_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
            workspace_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["workspace_id", b"workspace_id", "workspace_name", b"workspace_name"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["workspace_id", b"workspace_id", "workspace_name", b"workspace_name"]) -> None: ...

    PROJECT_ID_FIELD_NUMBER: builtins.int
    PROJECT_NAME_FIELD_NUMBER: builtins.int
    WORKSPACE_FIELD_NUMBER: builtins.int
    ALERT_OPS_CONFIGURATION_FIELD_NUMBER: builtins.int
    @property
    def project_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def project_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def workspace(self) -> global___AsanaProjectAssetModel.Workspace: ...
    @property
    def alert_ops_configuration(self) -> global___AsanaAlertOpsConfiguration: ...
    def __init__(
        self,
        *,
        project_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        project_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        workspace: global___AsanaProjectAssetModel.Workspace | None = ...,
        alert_ops_configuration: global___AsanaAlertOpsConfiguration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["alert_ops_configuration", b"alert_ops_configuration", "project_id", b"project_id", "project_name", b"project_name", "workspace", b"workspace"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["alert_ops_configuration", b"alert_ops_configuration", "project_id", b"project_id", "project_name", b"project_name", "workspace", b"workspace"]) -> None: ...

global___AsanaProjectAssetModel = AsanaProjectAssetModel

@typing_extensions.final
class AsanaProjectAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROJECT_IDS_FIELD_NUMBER: builtins.int
    @property
    def project_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        project_ids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["project_ids", b"project_ids"]) -> None: ...

global___AsanaProjectAssetOptions = AsanaProjectAssetOptions

@typing_extensions.final
class AsanaAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CONNECTOR_TYPE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    LAST_UPDATED_FIELD_NUMBER: builtins.int
    ASANA_PROJECT_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    connector_type: protos.base_pb2.Source.ValueType
    type: protos.base_pb2.SourceModelType.ValueType
    last_updated: builtins.int
    @property
    def asana_project(self) -> global___AsanaProjectAssetModel: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        connector_type: protos.base_pb2.Source.ValueType = ...,
        type: protos.base_pb2.SourceModelType.ValueType = ...,
        last_updated: builtins.int = ...,
        asana_project: global___AsanaProjectAssetModel | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["asana_project", b"asana_project", "asset", b"asset", "id", b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["asana_project", b"asana_project", "asset", b"asset", "connector_type", b"connector_type", "id", b"id", "last_updated", b"last_updated", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["asset", b"asset"]) -> typing_extensions.Literal["asana_project"] | None: ...

global___AsanaAssetModel = AsanaAssetModel

@typing_extensions.final
class AsanaAssets(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSETS_FIELD_NUMBER: builtins.int
    @property
    def assets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AsanaAssetModel]: ...
    def __init__(
        self,
        *,
        assets: collections.abc.Iterable[global___AsanaAssetModel] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["assets", b"assets"]) -> None: ...

global___AsanaAssets = AsanaAssets
