# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/assets/datadog_asset.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from protos import base_pb2 as protos_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!protos/assets/datadog_asset.proto\x12\x11protos.connectors\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x11protos/base.proto\"\x96\x02\n\x18\x44\x61tadogServiceAssetModel\x12\x32\n\x0cservice_name\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x14\n\x0c\x65nvironments\x18\x02 \x03(\t\x12\x43\n\x07metrics\x18\x03 \x03(\x0b\x32\x32.protos.connectors.DatadogServiceAssetModel.Metric\x1ak\n\x06Metric\x12\x33\n\rmetric_family\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12,\n\x06metric\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"\xd9\x01\n\x1a\x44\x61tadogServiceAssetOptions\x12Y\n\x08services\x18\x01 \x03(\x0b\x32G.protos.connectors.DatadogServiceAssetOptions.DatadogServiceAssetOption\x1a`\n\x19\x44\x61tadogServiceAssetOption\x12*\n\x04name\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x17\n\x0fmetric_families\x18\x02 \x03(\t\"\xf3\x01\n\x11\x44\x61tadogAssetModel\x12(\n\x02id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12&\n\x0e\x63onnector_type\x18\x02 \x01(\x0e\x32\x0e.protos.Source\x12%\n\x04type\x18\x03 \x01(\x0e\x32\x17.protos.SourceModelType\x12\x14\n\x0clast_updated\x18\x04 \x01(\x10\x12\x46\n\x0f\x64\x61tadog_service\x18\x05 \x01(\x0b\x32+.protos.connectors.DatadogServiceAssetModelH\x00\x42\x07\n\x05\x61sset\"E\n\rDatadogAssets\x12\x34\n\x06\x61ssets\x18\x01 \x03(\x0b\x32$.protos.connectors.DatadogAssetModelb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.assets.datadog_asset_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATADOGSERVICEASSETMODEL._serialized_start=108
  _DATADOGSERVICEASSETMODEL._serialized_end=386
  _DATADOGSERVICEASSETMODEL_METRIC._serialized_start=279
  _DATADOGSERVICEASSETMODEL_METRIC._serialized_end=386
  _DATADOGSERVICEASSETOPTIONS._serialized_start=389
  _DATADOGSERVICEASSETOPTIONS._serialized_end=606
  _DATADOGSERVICEASSETOPTIONS_DATADOGSERVICEASSETOPTION._serialized_start=510
  _DATADOGSERVICEASSETOPTIONS_DATADOGSERVICEASSETOPTION._serialized_end=606
  _DATADOGASSETMODEL._serialized_start=609
  _DATADOGASSETMODEL._serialized_end=852
  _DATADOGASSETS._serialized_start=854
  _DATADOGASSETS._serialized_end=923
# @@protoc_insertion_point(module_scope)
