"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import protos.base_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class GithubMember(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOGIN_FIELD_NUMBER: builtins.int
    @property
    def login(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        login: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["login", b"login"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["login", b"login"]) -> None: ...

global___GithubMember = GithubMember

@typing_extensions.final
class GithubRepositoryAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    FULL_NAME_FIELD_NUMBER: builtins.int
    HTML_URL_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    TOPICS_FIELD_NUMBER: builtins.int
    OWNER_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def full_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def html_url(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def description(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def topics(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def owner(self) -> global___GithubMember: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        full_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        html_url: google.protobuf.wrappers_pb2.StringValue | None = ...,
        description: google.protobuf.wrappers_pb2.StringValue | None = ...,
        topics: collections.abc.Iterable[builtins.str] | None = ...,
        owner: global___GithubMember | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["description", b"description", "full_name", b"full_name", "html_url", b"html_url", "id", b"id", "name", b"name", "owner", b"owner"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "full_name", b"full_name", "html_url", b"html_url", "id", b"id", "name", b"name", "owner", b"owner", "topics", b"topics"]) -> None: ...

global___GithubRepositoryAssetModel = GithubRepositoryAssetModel

@typing_extensions.final
class GithubMemberAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    LOGIN_FIELD_NUMBER: builtins.int
    HTML_URL_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def login(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def html_url(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        login: google.protobuf.wrappers_pb2.StringValue | None = ...,
        html_url: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["html_url", b"html_url", "id", b"id", "login", b"login"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["html_url", b"html_url", "id", b"id", "login", b"login"]) -> None: ...

global___GithubMemberAssetModel = GithubMemberAssetModel

@typing_extensions.final
class GithubRepositoryAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class GithubRepository(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        @property
        def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["name", b"name"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

    REPOSITORIES_FIELD_NUMBER: builtins.int
    @property
    def repositories(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GithubRepositoryAssetOptions.GithubRepository]: ...
    def __init__(
        self,
        *,
        repositories: collections.abc.Iterable[global___GithubRepositoryAssetOptions.GithubRepository] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["repositories", b"repositories"]) -> None: ...

global___GithubRepositoryAssetOptions = GithubRepositoryAssetOptions

@typing_extensions.final
class GithubMemberAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MEMBERS_FIELD_NUMBER: builtins.int
    @property
    def members(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GithubMember]: ...
    def __init__(
        self,
        *,
        members: collections.abc.Iterable[global___GithubMember] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["members", b"members"]) -> None: ...

global___GithubMemberAssetOptions = GithubMemberAssetOptions

@typing_extensions.final
class GithubAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CONNECTOR_TYPE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    LAST_UPDATED_FIELD_NUMBER: builtins.int
    GITHUB_REPOSITORY_FIELD_NUMBER: builtins.int
    GITHUB_MEMBER_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    connector_type: protos.base_pb2.Source.ValueType
    type: protos.base_pb2.SourceModelType.ValueType
    last_updated: builtins.int
    @property
    def github_repository(self) -> global___GithubRepositoryAssetModel: ...
    @property
    def github_member(self) -> global___GithubMemberAssetModel: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        connector_type: protos.base_pb2.Source.ValueType = ...,
        type: protos.base_pb2.SourceModelType.ValueType = ...,
        last_updated: builtins.int = ...,
        github_repository: global___GithubRepositoryAssetModel | None = ...,
        github_member: global___GithubMemberAssetModel | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["asset", b"asset", "github_member", b"github_member", "github_repository", b"github_repository", "id", b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["asset", b"asset", "connector_type", b"connector_type", "github_member", b"github_member", "github_repository", b"github_repository", "id", b"id", "last_updated", b"last_updated", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["asset", b"asset"]) -> typing_extensions.Literal["github_repository", "github_member"] | None: ...

global___GithubAssetModel = GithubAssetModel

@typing_extensions.final
class GithubAssets(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSETS_FIELD_NUMBER: builtins.int
    @property
    def assets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GithubAssetModel]: ...
    def __init__(
        self,
        *,
        assets: collections.abc.Iterable[global___GithubAssetModel] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["assets", b"assets"]) -> None: ...

global___GithubAssets = GithubAssets
