# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/assets/gke_asset.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from protos import base_pb2 as protos_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dprotos/assets/gke_asset.proto\x12\rprotos.assets\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x11protos/base.proto\"k\n\nGkeCommand\x12*\n\x04type\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x31\n\x0b\x64\x65scription\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"H\n\x0cGkeNamespace\x12*\n\x04name\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x0c\n\x04pods\x18\x02 \x03(\t\"i\n\nGkeCluster\x12*\n\x04name\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12/\n\nnamespaces\x18\x02 \x03(\x0b\x32\x1b.protos.assets.GkeNamespace\"f\n\x0bZoneCluster\x12*\n\x04zone\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12+\n\x08\x63lusters\x18\x02 \x03(\x0b\x32\x19.protos.assets.GkeCluster\"\x9c\x01\n\x14GkeClusterAssetModel\x12*\n\x04zone\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12+\n\x08\x63lusters\x18\x02 \x03(\x0b\x32\x19.protos.assets.GkeCluster\x12+\n\x08\x63ommands\x18\x03 \x03(\x0b\x32\x19.protos.assets.GkeCommand\"C\n\x16GkeClusterAssetOptions\x12)\n\x05zones\x18\x01 \x03(\x0b\x32\x1a.protos.assets.ZoneCluster\"\xe3\x01\n\rGkeAssetModel\x12(\n\x02id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12&\n\x0e\x63onnector_type\x18\x02 \x01(\x0e\x32\x0e.protos.Source\x12%\n\x04type\x18\x03 \x01(\x0e\x32\x17.protos.SourceModelType\x12\x14\n\x0clast_updated\x18\x04 \x01(\x10\x12:\n\x0bgke_cluster\x18\x05 \x01(\x0b\x32#.protos.assets.GkeClusterAssetModelH\x00\x42\x07\n\x05\x61sset\"9\n\tGkeAssets\x12,\n\x06\x61ssets\x18\x01 \x03(\x0b\x32\x1c.protos.assets.GkeAssetModelb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.assets.gke_asset_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GKECOMMAND._serialized_start=99
  _GKECOMMAND._serialized_end=206
  _GKENAMESPACE._serialized_start=208
  _GKENAMESPACE._serialized_end=280
  _GKECLUSTER._serialized_start=282
  _GKECLUSTER._serialized_end=387
  _ZONECLUSTER._serialized_start=389
  _ZONECLUSTER._serialized_end=491
  _GKECLUSTERASSETMODEL._serialized_start=494
  _GKECLUSTERASSETMODEL._serialized_end=650
  _GKECLUSTERASSETOPTIONS._serialized_start=652
  _GKECLUSTERASSETOPTIONS._serialized_end=719
  _GKEASSETMODEL._serialized_start=722
  _GKEASSETMODEL._serialized_end=949
  _GKEASSETS._serialized_start=951
  _GKEASSETS._serialized_end=1008
# @@protoc_insertion_point(module_scope)
