"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.struct_pb2
import google.protobuf.wrappers_pb2
import protos.base_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class SignozDashboardPanelModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Query(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ID_FIELD_NUMBER: builtins.int
        NAME_FIELD_NUMBER: builtins.int
        QUERY_FIELD_NUMBER: builtins.int
        LEGEND_FIELD_NUMBER: builtins.int
        DISABLED_FIELD_NUMBER: builtins.int
        @property
        def id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def query(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def legend(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def disabled(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        def __init__(
            self,
            *,
            id: google.protobuf.wrappers_pb2.StringValue | None = ...,
            name: google.protobuf.wrappers_pb2.StringValue | None = ...,
            query: google.protobuf.wrappers_pb2.StringValue | None = ...,
            legend: google.protobuf.wrappers_pb2.StringValue | None = ...,
            disabled: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["disabled", b"disabled", "id", b"id", "legend", b"legend", "name", b"name", "query", b"query"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["disabled", b"disabled", "id", b"id", "legend", b"legend", "name", b"name", "query", b"query"]) -> None: ...

    @typing_extensions.final
    class QueryData(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        LIMIT_FIELD_NUMBER: builtins.int
        LEGEND_FIELD_NUMBER: builtins.int
        FILTERS_FIELD_NUMBER: builtins.int
        GROUP_BY_FIELD_NUMBER: builtins.int
        ORDER_BY_FIELD_NUMBER: builtins.int
        DISABLED_FIELD_NUMBER: builtins.int
        REDUCETO_FIELD_NUMBER: builtins.int
        FUNCTIONS_FIELD_NUMBER: builtins.int
        QUERYNAME_FIELD_NUMBER: builtins.int
        DATASOURCE_FIELD_NUMBER: builtins.int
        EXPRESSION_FIELD_NUMBER: builtins.int
        STEP_INTERVAL_FIELD_NUMBER: builtins.int
        TIMEAGGREGATION_FIELD_NUMBER: builtins.int
        SPACEAGGREGATION_FIELD_NUMBER: builtins.int
        AGGREGATEOPERATOR_FIELD_NUMBER: builtins.int
        AGGREGATEATTRIBUTE_FIELD_NUMBER: builtins.int
        @property
        def limit(self) -> google.protobuf.wrappers_pb2.Int32Value: ...
        @property
        def legend(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def filters(self) -> google.protobuf.struct_pb2.Struct: ...
        @property
        def group_by(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
        @property
        def order_by(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
        @property
        def disabled(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        @property
        def reduceTo(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def functions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
        @property
        def queryName(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def dataSource(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def expression(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def step_interval(self) -> google.protobuf.wrappers_pb2.Int32Value: ...
        @property
        def timeAggregation(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def spaceAggregation(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def aggregateOperator(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def aggregateAttribute(self) -> google.protobuf.struct_pb2.Struct: ...
        def __init__(
            self,
            *,
            limit: google.protobuf.wrappers_pb2.Int32Value | None = ...,
            legend: google.protobuf.wrappers_pb2.StringValue | None = ...,
            filters: google.protobuf.struct_pb2.Struct | None = ...,
            group_by: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
            order_by: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
            disabled: google.protobuf.wrappers_pb2.BoolValue | None = ...,
            reduceTo: google.protobuf.wrappers_pb2.StringValue | None = ...,
            functions: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
            queryName: google.protobuf.wrappers_pb2.StringValue | None = ...,
            dataSource: google.protobuf.wrappers_pb2.StringValue | None = ...,
            expression: google.protobuf.wrappers_pb2.StringValue | None = ...,
            step_interval: google.protobuf.wrappers_pb2.Int32Value | None = ...,
            timeAggregation: google.protobuf.wrappers_pb2.StringValue | None = ...,
            spaceAggregation: google.protobuf.wrappers_pb2.StringValue | None = ...,
            aggregateOperator: google.protobuf.wrappers_pb2.StringValue | None = ...,
            aggregateAttribute: google.protobuf.struct_pb2.Struct | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["aggregateAttribute", b"aggregateAttribute", "aggregateOperator", b"aggregateOperator", "dataSource", b"dataSource", "disabled", b"disabled", "expression", b"expression", "filters", b"filters", "legend", b"legend", "limit", b"limit", "queryName", b"queryName", "reduceTo", b"reduceTo", "spaceAggregation", b"spaceAggregation", "step_interval", b"step_interval", "timeAggregation", b"timeAggregation"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["aggregateAttribute", b"aggregateAttribute", "aggregateOperator", b"aggregateOperator", "dataSource", b"dataSource", "disabled", b"disabled", "expression", b"expression", "filters", b"filters", "functions", b"functions", "group_by", b"group_by", "legend", b"legend", "limit", b"limit", "order_by", b"order_by", "queryName", b"queryName", "reduceTo", b"reduceTo", "spaceAggregation", b"spaceAggregation", "step_interval", b"step_interval", "timeAggregation", b"timeAggregation"]) -> None: ...

    @typing_extensions.final
    class QueryBuilder(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        QUERY_DATA_FIELD_NUMBER: builtins.int
        QUERY_FORMULAS_FIELD_NUMBER: builtins.int
        @property
        def query_data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SignozDashboardPanelModel.QueryData]: ...
        @property
        def query_formulas(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
        def __init__(
            self,
            *,
            query_data: collections.abc.Iterable[global___SignozDashboardPanelModel.QueryData] | None = ...,
            query_formulas: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["query_data", b"query_data", "query_formulas", b"query_formulas"]) -> None: ...

    @typing_extensions.final
    class PanelQuery(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ID_FIELD_NUMBER: builtins.int
        PROMQL_FIELD_NUMBER: builtins.int
        BUILDER_FIELD_NUMBER: builtins.int
        QUERY_TYPE_FIELD_NUMBER: builtins.int
        CLICKHOUSE_SQL_FIELD_NUMBER: builtins.int
        @property
        def id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def promql(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SignozDashboardPanelModel.Query]: ...
        @property
        def builder(self) -> global___SignozDashboardPanelModel.QueryBuilder: ...
        @property
        def query_type(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def clickhouse_sql(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SignozDashboardPanelModel.Query]: ...
        def __init__(
            self,
            *,
            id: google.protobuf.wrappers_pb2.StringValue | None = ...,
            promql: collections.abc.Iterable[global___SignozDashboardPanelModel.Query] | None = ...,
            builder: global___SignozDashboardPanelModel.QueryBuilder | None = ...,
            query_type: google.protobuf.wrappers_pb2.StringValue | None = ...,
            clickhouse_sql: collections.abc.Iterable[global___SignozDashboardPanelModel.Query] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["builder", b"builder", "id", b"id", "query_type", b"query_type"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["builder", b"builder", "clickhouse_sql", b"clickhouse_sql", "id", b"id", "promql", b"promql", "query_type", b"query_type"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    QUERY_FIELD_NUMBER: builtins.int
    PANEL_TYPE_FIELD_NUMBER: builtins.int
    OPACITY_FIELD_NUMBER: builtins.int
    SOFT_MAX_FIELD_NUMBER: builtins.int
    SOFT_MIN_FIELD_NUMBER: builtins.int
    FILL_SPANS_FIELD_NUMBER: builtins.int
    IS_STACKED_FIELD_NUMBER: builtins.int
    Y_AXIS_UNIT_FIELD_NUMBER: builtins.int
    THRESHOLDS_FIELD_NUMBER: builtins.int
    BUCKET_COUNT_FIELD_NUMBER: builtins.int
    BUCKET_WIDTH_FIELD_NUMBER: builtins.int
    COLUMN_UNITS_FIELD_NUMBER: builtins.int
    NULL_ZERO_VALUES_FIELD_NUMBER: builtins.int
    TIME_PREFERENCE_FIELD_NUMBER: builtins.int
    STACKED_BAR_CHART_FIELD_NUMBER: builtins.int
    SELECTED_LOG_FIELDS_FIELD_NUMBER: builtins.int
    SELECTED_TRACES_FIELDS_FIELD_NUMBER: builtins.int
    MERGE_ALL_ACTIVE_QUERIES_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def title(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def description(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def query(self) -> global___SignozDashboardPanelModel.PanelQuery: ...
    @property
    def panel_type(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def opacity(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def soft_max(self) -> google.protobuf.wrappers_pb2.Int32Value: ...
    @property
    def soft_min(self) -> google.protobuf.wrappers_pb2.Int32Value: ...
    @property
    def fill_spans(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def is_stacked(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def y_axis_unit(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def thresholds(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
    @property
    def bucket_count(self) -> google.protobuf.wrappers_pb2.Int32Value: ...
    @property
    def bucket_width(self) -> google.protobuf.wrappers_pb2.Int32Value: ...
    @property
    def column_units(self) -> google.protobuf.struct_pb2.Struct: ...
    @property
    def null_zero_values(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def time_preference(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def stacked_bar_chart(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def selected_log_fields(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
    @property
    def selected_traces_fields(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
    @property
    def merge_all_active_queries(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        title: google.protobuf.wrappers_pb2.StringValue | None = ...,
        description: google.protobuf.wrappers_pb2.StringValue | None = ...,
        query: global___SignozDashboardPanelModel.PanelQuery | None = ...,
        panel_type: google.protobuf.wrappers_pb2.StringValue | None = ...,
        opacity: google.protobuf.wrappers_pb2.StringValue | None = ...,
        soft_max: google.protobuf.wrappers_pb2.Int32Value | None = ...,
        soft_min: google.protobuf.wrappers_pb2.Int32Value | None = ...,
        fill_spans: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        is_stacked: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        y_axis_unit: google.protobuf.wrappers_pb2.StringValue | None = ...,
        thresholds: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        bucket_count: google.protobuf.wrappers_pb2.Int32Value | None = ...,
        bucket_width: google.protobuf.wrappers_pb2.Int32Value | None = ...,
        column_units: google.protobuf.struct_pb2.Struct | None = ...,
        null_zero_values: google.protobuf.wrappers_pb2.StringValue | None = ...,
        time_preference: google.protobuf.wrappers_pb2.StringValue | None = ...,
        stacked_bar_chart: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        selected_log_fields: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        selected_traces_fields: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        merge_all_active_queries: google.protobuf.wrappers_pb2.BoolValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bucket_count", b"bucket_count", "bucket_width", b"bucket_width", "column_units", b"column_units", "description", b"description", "fill_spans", b"fill_spans", "id", b"id", "is_stacked", b"is_stacked", "merge_all_active_queries", b"merge_all_active_queries", "null_zero_values", b"null_zero_values", "opacity", b"opacity", "panel_type", b"panel_type", "query", b"query", "soft_max", b"soft_max", "soft_min", b"soft_min", "stacked_bar_chart", b"stacked_bar_chart", "time_preference", b"time_preference", "title", b"title", "y_axis_unit", b"y_axis_unit"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bucket_count", b"bucket_count", "bucket_width", b"bucket_width", "column_units", b"column_units", "description", b"description", "fill_spans", b"fill_spans", "id", b"id", "is_stacked", b"is_stacked", "merge_all_active_queries", b"merge_all_active_queries", "null_zero_values", b"null_zero_values", "opacity", b"opacity", "panel_type", b"panel_type", "query", b"query", "selected_log_fields", b"selected_log_fields", "selected_traces_fields", b"selected_traces_fields", "soft_max", b"soft_max", "soft_min", b"soft_min", "stacked_bar_chart", b"stacked_bar_chart", "thresholds", b"thresholds", "time_preference", b"time_preference", "title", b"title", "y_axis_unit", b"y_axis_unit"]) -> None: ...

global___SignozDashboardPanelModel = SignozDashboardPanelModel

@typing_extensions.final
class SignozDashboardVariableModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    SELECTED_VALUE_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def description(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def type(self) -> google.protobuf.wrappers_pb2.StringValue:
        """e.g., TEXTBOX, QUERY, etc."""
    @property
    def selected_value(self) -> google.protobuf.wrappers_pb2.StringValue:
        """Default/selected value"""
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        description: google.protobuf.wrappers_pb2.StringValue | None = ...,
        type: google.protobuf.wrappers_pb2.StringValue | None = ...,
        selected_value: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["description", b"description", "id", b"id", "name", b"name", "selected_value", b"selected_value", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "id", b"id", "name", b"name", "selected_value", b"selected_value", "type", b"type"]) -> None: ...

global___SignozDashboardVariableModel = SignozDashboardVariableModel

@typing_extensions.final
class SignozDashboardModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    UUID_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    PANELS_FIELD_NUMBER: builtins.int
    VARIABLES_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def uuid(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def url(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def title(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def description(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def panels(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SignozDashboardPanelModel]: ...
    @property
    def variables(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SignozDashboardVariableModel]: ...
    @property
    def created_at(self) -> google.protobuf.wrappers_pb2.Int64Value: ...
    @property
    def updated_at(self) -> google.protobuf.wrappers_pb2.Int64Value: ...
    @property
    def tags(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        uuid: google.protobuf.wrappers_pb2.StringValue | None = ...,
        url: google.protobuf.wrappers_pb2.StringValue | None = ...,
        title: google.protobuf.wrappers_pb2.StringValue | None = ...,
        description: google.protobuf.wrappers_pb2.StringValue | None = ...,
        panels: collections.abc.Iterable[global___SignozDashboardPanelModel] | None = ...,
        variables: collections.abc.Iterable[global___SignozDashboardVariableModel] | None = ...,
        created_at: google.protobuf.wrappers_pb2.Int64Value | None = ...,
        updated_at: google.protobuf.wrappers_pb2.Int64Value | None = ...,
        tags: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "description", b"description", "id", b"id", "tags", b"tags", "title", b"title", "updated_at", b"updated_at", "url", b"url", "uuid", b"uuid"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "description", b"description", "id", b"id", "panels", b"panels", "tags", b"tags", "title", b"title", "updated_at", b"updated_at", "url", b"url", "uuid", b"uuid", "variables", b"variables"]) -> None: ...

global___SignozDashboardModel = SignozDashboardModel

@typing_extensions.final
class SignozAlertModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    QUERY_FIELD_NUMBER: builtins.int
    CONDITION_FIELD_NUMBER: builtins.int
    THRESHOLD_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    EVALUATION_WINDOW_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    ENABLED_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def description(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def query(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def condition(self) -> google.protobuf.wrappers_pb2.StringValue:
        """e.g., ">", "<", "==" """
    @property
    def threshold(self) -> google.protobuf.wrappers_pb2.DoubleValue: ...
    @property
    def severity(self) -> google.protobuf.wrappers_pb2.StringValue:
        """e.g., "critical", "warning", "info" """
    @property
    def evaluation_window(self) -> google.protobuf.wrappers_pb2.StringValue:
        """Time window for evaluation"""
    @property
    def tags(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def created_at(self) -> google.protobuf.wrappers_pb2.Int64Value: ...
    @property
    def updated_at(self) -> google.protobuf.wrappers_pb2.Int64Value: ...
    @property
    def enabled(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        description: google.protobuf.wrappers_pb2.StringValue | None = ...,
        query: google.protobuf.wrappers_pb2.StringValue | None = ...,
        condition: google.protobuf.wrappers_pb2.StringValue | None = ...,
        threshold: google.protobuf.wrappers_pb2.DoubleValue | None = ...,
        severity: google.protobuf.wrappers_pb2.StringValue | None = ...,
        evaluation_window: google.protobuf.wrappers_pb2.StringValue | None = ...,
        tags: google.protobuf.wrappers_pb2.StringValue | None = ...,
        created_at: google.protobuf.wrappers_pb2.Int64Value | None = ...,
        updated_at: google.protobuf.wrappers_pb2.Int64Value | None = ...,
        enabled: google.protobuf.wrappers_pb2.BoolValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["condition", b"condition", "created_at", b"created_at", "description", b"description", "enabled", b"enabled", "evaluation_window", b"evaluation_window", "id", b"id", "name", b"name", "query", b"query", "severity", b"severity", "tags", b"tags", "threshold", b"threshold", "updated_at", b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["condition", b"condition", "created_at", b"created_at", "description", b"description", "enabled", b"enabled", "evaluation_window", b"evaluation_window", "id", b"id", "name", b"name", "query", b"query", "severity", b"severity", "tags", b"tags", "threshold", b"threshold", "updated_at", b"updated_at"]) -> None: ...

global___SignozAlertModel = SignozAlertModel

@typing_extensions.final
class SignozAssetModel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CONNECTOR_TYPE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    LAST_UPDATED_FIELD_NUMBER: builtins.int
    SIGNOZ_DASHBOARD_FIELD_NUMBER: builtins.int
    SIGNOZ_ALERT_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    connector_type: protos.base_pb2.Source.ValueType
    type: protos.base_pb2.SourceModelType.ValueType
    last_updated: builtins.int
    @property
    def signoz_dashboard(self) -> global___SignozDashboardModel: ...
    @property
    def signoz_alert(self) -> global___SignozAlertModel: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        connector_type: protos.base_pb2.Source.ValueType = ...,
        type: protos.base_pb2.SourceModelType.ValueType = ...,
        last_updated: builtins.int = ...,
        signoz_dashboard: global___SignozDashboardModel | None = ...,
        signoz_alert: global___SignozAlertModel | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["asset", b"asset", "id", b"id", "signoz_alert", b"signoz_alert", "signoz_dashboard", b"signoz_dashboard"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["asset", b"asset", "connector_type", b"connector_type", "id", b"id", "last_updated", b"last_updated", "signoz_alert", b"signoz_alert", "signoz_dashboard", b"signoz_dashboard", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["asset", b"asset"]) -> typing_extensions.Literal["signoz_dashboard", "signoz_alert"] | None: ...

global___SignozAssetModel = SignozAssetModel

@typing_extensions.final
class SignozAssets(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASSETS_FIELD_NUMBER: builtins.int
    @property
    def assets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SignozAssetModel]: ...
    def __init__(
        self,
        *,
        assets: collections.abc.Iterable[global___SignozAssetModel] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["assets", b"assets"]) -> None: ...

global___SignozAssets = SignozAssets

@typing_extensions.final
class SignozDashboardAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DASHBOARDS_FIELD_NUMBER: builtins.int
    @property
    def dashboards(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        dashboards: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["dashboards", b"dashboards"]) -> None: ...

global___SignozDashboardAssetOptions = SignozDashboardAssetOptions

@typing_extensions.final
class SignozAlertAssetOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALERTS_FIELD_NUMBER: builtins.int
    @property
    def alerts(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        alerts: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["alerts", b"alerts"]) -> None: ...

global___SignozAlertAssetOptions = SignozAlertAssetOptions
