# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/playbooks/source_task_definitions/argocd_task.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:protos/playbooks/source_task_definitions/argocd_task.proto\x12\x10protos.playbooks\x1a\x1egoogle/protobuf/wrappers.proto\"\xd2\x04\n\x06\x41rgoCD\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.protos.playbooks.ArgoCD.TaskType\x12M\n\x15\x66\x65tch_deployment_info\x18\x02 \x01(\x0b\x32,.protos.playbooks.ArgoCD.FetchDeploymentInfoH\x00\x12L\n\x14rollback_application\x18\x03 \x01(\x0b\x32,.protos.playbooks.ArgoCD.RollbackApplicationH\x00\x1a\xad\x01\n\x13\x46\x65tchDeploymentInfo\x12*\n\x05\x63ount\x18\x01 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12.\n\x08\x61pp_name\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12:\n\x15time_since_in_minutes\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x1at\n\x13RollbackApplication\x12.\n\x08\x61pp_name\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12-\n\x07version\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"L\n\x08TaskType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x19\n\x15\x46\x45TCH_DEPLOYMENT_INFO\x10\x01\x12\x18\n\x14ROLLBACK_APPLICATION\x10\x02\x42\x06\n\x04taskb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.playbooks.source_task_definitions.argocd_task_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ARGOCD._serialized_start=113
  _ARGOCD._serialized_end=707
  _ARGOCD_FETCHDEPLOYMENTINFO._serialized_start=330
  _ARGOCD_FETCHDEPLOYMENTINFO._serialized_end=503
  _ARGOCD_ROLLBACKAPPLICATION._serialized_start=505
  _ARGOCD_ROLLBACKAPPLICATION._serialized_end=621
  _ARGOCD_TASKTYPE._serialized_start=623
  _ARGOCD_TASKTYPE._serialized_end=699
# @@protoc_insertion_point(module_scope)
