"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.struct_pb2
import google.protobuf.wrappers_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Datadog(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _TaskType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TaskTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Datadog._TaskType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: Datadog._TaskType.ValueType  # 0
        SERVICE_METRIC_EXECUTION: Datadog._TaskType.ValueType  # 1
        QUERY_METRIC_EXECUTION: Datadog._TaskType.ValueType  # 2
        LOG_QUERY_EXECUTION: Datadog._TaskType.ValueType  # 3
        QUERY_DASHBOARD_WIDGET_METRIC: Datadog._TaskType.ValueType  # 4
        LOG_COUNT_BY_SERVICE_EXECUTION: Datadog._TaskType.ValueType  # 5
        DASHBOARD_MULTIPLE_WIDGETS: Datadog._TaskType.ValueType  # 6
        APM_QUERY: Datadog._TaskType.ValueType  # 7

    class TaskType(_TaskType, metaclass=_TaskTypeEnumTypeWrapper): ...
    UNKNOWN: Datadog.TaskType.ValueType  # 0
    SERVICE_METRIC_EXECUTION: Datadog.TaskType.ValueType  # 1
    QUERY_METRIC_EXECUTION: Datadog.TaskType.ValueType  # 2
    LOG_QUERY_EXECUTION: Datadog.TaskType.ValueType  # 3
    QUERY_DASHBOARD_WIDGET_METRIC: Datadog.TaskType.ValueType  # 4
    LOG_COUNT_BY_SERVICE_EXECUTION: Datadog.TaskType.ValueType  # 5
    DASHBOARD_MULTIPLE_WIDGETS: Datadog.TaskType.ValueType  # 6
    APM_QUERY: Datadog.TaskType.ValueType  # 7

    @typing_extensions.final
    class ServiceMetricExecutionTask(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SERVICE_NAME_FIELD_NUMBER: builtins.int
        ENVIRONMENT_NAME_FIELD_NUMBER: builtins.int
        METRIC_FAMILY_FIELD_NUMBER: builtins.int
        METRIC_FIELD_NUMBER: builtins.int
        TIMESERIES_OFFSETS_FIELD_NUMBER: builtins.int
        INTERVAL_FIELD_NUMBER: builtins.int
        @property
        def service_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def environment_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def metric_family(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def metric(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def timeseries_offsets(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        @property
        def interval(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        def __init__(
            self,
            *,
            service_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
            environment_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
            metric_family: google.protobuf.wrappers_pb2.StringValue | None = ...,
            metric: google.protobuf.wrappers_pb2.StringValue | None = ...,
            timeseries_offsets: collections.abc.Iterable[builtins.int] | None = ...,
            interval: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["environment_name", b"environment_name", "interval", b"interval", "metric", b"metric", "metric_family", b"metric_family", "service_name", b"service_name"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["environment_name", b"environment_name", "interval", b"interval", "metric", b"metric", "metric_family", b"metric_family", "service_name", b"service_name", "timeseries_offsets", b"timeseries_offsets"]) -> None: ...

    @typing_extensions.final
    class QueryMetricExecutionTask(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        QUERIES_FIELD_NUMBER: builtins.int
        FORMULA_FIELD_NUMBER: builtins.int
        TIMESERIES_OFFSETS_FIELD_NUMBER: builtins.int
        INTERVAL_FIELD_NUMBER: builtins.int
        @property
        def queries(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
        @property
        def formula(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def timeseries_offsets(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        interval: builtins.int
        def __init__(
            self,
            *,
            queries: collections.abc.Iterable[builtins.str] | None = ...,
            formula: google.protobuf.wrappers_pb2.StringValue | None = ...,
            timeseries_offsets: collections.abc.Iterable[builtins.int] | None = ...,
            interval: builtins.int = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["formula", b"formula"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["formula", b"formula", "interval", b"interval", "queries", b"queries", "timeseries_offsets", b"timeseries_offsets"]) -> None: ...

    @typing_extensions.final
    class QueryDashboardWidgetMetricTask(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        RESPONSE_TYPE_FIELD_NUMBER: builtins.int
        QUERIES_FIELD_NUMBER: builtins.int
        FORMULAS_FIELD_NUMBER: builtins.int
        DASHBOARD_FIELD_NUMBER: builtins.int
        WIDGET_ID_FIELD_NUMBER: builtins.int
        WIDGET_TITLE_FIELD_NUMBER: builtins.int
        WIDGET_TYPE_FIELD_NUMBER: builtins.int
        @property
        def response_type(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def queries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
        @property
        def formulas(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
        @property
        def dashboard(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def widget_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def widget_title(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def widget_type(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            response_type: google.protobuf.wrappers_pb2.StringValue | None = ...,
            queries: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
            formulas: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
            dashboard: google.protobuf.wrappers_pb2.StringValue | None = ...,
            widget_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
            widget_title: google.protobuf.wrappers_pb2.StringValue | None = ...,
            widget_type: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["dashboard", b"dashboard", "response_type", b"response_type", "widget_id", b"widget_id", "widget_title", b"widget_title", "widget_type", b"widget_type"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["dashboard", b"dashboard", "formulas", b"formulas", "queries", b"queries", "response_type", b"response_type", "widget_id", b"widget_id", "widget_title", b"widget_title", "widget_type", b"widget_type"]) -> None: ...

    @typing_extensions.final
    class LogQueryExecutionTask(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        QUERY_FIELD_NUMBER: builtins.int
        @property
        def query(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            query: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["query", b"query"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["query", b"query"]) -> None: ...

    @typing_extensions.final
    class LogCountByServiceExecutionTask(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        QUERY_FIELD_NUMBER: builtins.int
        @property
        def query(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            query: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["query", b"query"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["query", b"query"]) -> None: ...

    @typing_extensions.final
    class DashboardMultipleWidgetsTask(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        DASHBOARD_NAME_FIELD_NUMBER: builtins.int
        WIDGET_ID_FIELD_NUMBER: builtins.int
        UNIT_FIELD_NUMBER: builtins.int
        TIMESERIES_OFFSETS_FIELD_NUMBER: builtins.int
        INTERVAL_FIELD_NUMBER: builtins.int
        TEMPLATE_VARIABLES_FIELD_NUMBER: builtins.int
        @property
        def dashboard_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def widget_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def unit(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def timeseries_offsets(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        @property
        def interval(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        @property
        def template_variables(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            dashboard_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
            widget_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
            unit: google.protobuf.wrappers_pb2.StringValue | None = ...,
            timeseries_offsets: collections.abc.Iterable[builtins.int] | None = ...,
            interval: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
            template_variables: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["dashboard_name", b"dashboard_name", "interval", b"interval", "template_variables", b"template_variables", "unit", b"unit", "widget_id", b"widget_id"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["dashboard_name", b"dashboard_name", "interval", b"interval", "template_variables", b"template_variables", "timeseries_offsets", b"timeseries_offsets", "unit", b"unit", "widget_id", b"widget_id"]) -> None: ...

    @typing_extensions.final
    class APMQuery(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SERVICE_NAME_FIELD_NUMBER: builtins.int
        INTERVAL_FIELD_NUMBER: builtins.int
        @property
        def service_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def interval(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        def __init__(
            self,
            *,
            service_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
            interval: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["interval", b"interval", "service_name", b"service_name"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["interval", b"interval", "service_name", b"service_name"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    SERVICE_METRIC_EXECUTION_FIELD_NUMBER: builtins.int
    QUERY_METRIC_EXECUTION_FIELD_NUMBER: builtins.int
    LOG_QUERY_EXECUTION_FIELD_NUMBER: builtins.int
    QUERY_DASHBOARD_WIDGET_METRIC_FIELD_NUMBER: builtins.int
    LOG_COUNT_BY_SERVICE_EXECUTION_FIELD_NUMBER: builtins.int
    DASHBOARD_MULTIPLE_WIDGETS_FIELD_NUMBER: builtins.int
    APM_QUERY_FIELD_NUMBER: builtins.int
    type: global___Datadog.TaskType.ValueType
    @property
    def service_metric_execution(self) -> global___Datadog.ServiceMetricExecutionTask: ...
    @property
    def query_metric_execution(self) -> global___Datadog.QueryMetricExecutionTask: ...
    @property
    def log_query_execution(self) -> global___Datadog.LogQueryExecutionTask: ...
    @property
    def query_dashboard_widget_metric(self) -> global___Datadog.QueryDashboardWidgetMetricTask: ...
    @property
    def log_count_by_service_execution(self) -> global___Datadog.LogCountByServiceExecutionTask: ...
    @property
    def dashboard_multiple_widgets(self) -> global___Datadog.DashboardMultipleWidgetsTask: ...
    @property
    def apm_query(self) -> global___Datadog.APMQuery: ...
    def __init__(
        self,
        *,
        type: global___Datadog.TaskType.ValueType = ...,
        service_metric_execution: global___Datadog.ServiceMetricExecutionTask | None = ...,
        query_metric_execution: global___Datadog.QueryMetricExecutionTask | None = ...,
        log_query_execution: global___Datadog.LogQueryExecutionTask | None = ...,
        query_dashboard_widget_metric: global___Datadog.QueryDashboardWidgetMetricTask | None = ...,
        log_count_by_service_execution: global___Datadog.LogCountByServiceExecutionTask | None = ...,
        dashboard_multiple_widgets: global___Datadog.DashboardMultipleWidgetsTask | None = ...,
        apm_query: global___Datadog.APMQuery | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["apm_query", b"apm_query", "dashboard_multiple_widgets", b"dashboard_multiple_widgets", "log_count_by_service_execution", b"log_count_by_service_execution", "log_query_execution", b"log_query_execution", "query_dashboard_widget_metric", b"query_dashboard_widget_metric", "query_metric_execution", b"query_metric_execution", "service_metric_execution", b"service_metric_execution", "task", b"task"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["apm_query", b"apm_query", "dashboard_multiple_widgets", b"dashboard_multiple_widgets", "log_count_by_service_execution", b"log_count_by_service_execution", "log_query_execution", b"log_query_execution", "query_dashboard_widget_metric", b"query_dashboard_widget_metric", "query_metric_execution", b"query_metric_execution", "service_metric_execution", b"service_metric_execution", "task", b"task", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["task", b"task"]) -> typing_extensions.Literal["service_metric_execution", "query_metric_execution", "log_query_execution", "query_dashboard_widget_metric", "log_count_by_service_execution", "dashboard_multiple_widgets", "apm_query"] | None: ...

global___Datadog = Datadog
