"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.wrappers_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class GithubActions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _TaskType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TaskTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[GithubActions._TaskType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: GithubActions._TaskType.ValueType  # 0
        FETCH_ACTION_RUN_INFO: GithubActions._TaskType.ValueType  # 1

    class TaskType(_TaskType, metaclass=_TaskTypeEnumTypeWrapper): ...
    UNKNOWN: GithubActions.TaskType.ValueType  # 0
    FETCH_ACTION_RUN_INFO: GithubActions.TaskType.ValueType  # 1

    @typing_extensions.final
    class FetchActionRunInfo(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        OWNER_FIELD_NUMBER: builtins.int
        REPO_FIELD_NUMBER: builtins.int
        WORKFLOW_ID_FIELD_NUMBER: builtins.int
        @property
        def owner(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def repo(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def workflow_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            owner: google.protobuf.wrappers_pb2.StringValue | None = ...,
            repo: google.protobuf.wrappers_pb2.StringValue | None = ...,
            workflow_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["owner", b"owner", "repo", b"repo", "workflow_id", b"workflow_id"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["owner", b"owner", "repo", b"repo", "workflow_id", b"workflow_id"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    FETCH_ACTION_RUN_INFO_FIELD_NUMBER: builtins.int
    type: global___GithubActions.TaskType.ValueType
    @property
    def fetch_action_run_info(self) -> global___GithubActions.FetchActionRunInfo: ...
    def __init__(
        self,
        *,
        type: global___GithubActions.TaskType.ValueType = ...,
        fetch_action_run_info: global___GithubActions.FetchActionRunInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["fetch_action_run_info", b"fetch_action_run_info", "task", b"task"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["fetch_action_run_info", b"fetch_action_run_info", "task", b"task", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["task", b"task"]) -> typing_extensions.Literal["fetch_action_run_info"] | None: ...

global___GithubActions = GithubActions
