# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/playbooks/source_task_definitions/jenkins_task.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;protos/playbooks/source_task_definitions/jenkins_task.proto\x12\x10protos.playbooks\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xee\x03\n\x07Jenkins\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".protos.playbooks.Jenkins.TaskType\x12N\n\x18\x66\x65tch_last_build_details\x18\x02 \x01(\x0b\x32*.protos.playbooks.Jenkins.LastBuildDetailsH\x00\x12\x33\n\x07run_job\x18\x03 \x01(\x0b\x32 .protos.playbooks.Jenkins.RunJobH\x00\x1a\x42\n\x10LastBuildDetails\x12.\n\x08job_name\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x1a\x9b\x01\n\x06RunJob\x12.\n\x08job_name\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x30\n\nparameters\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12/\n\x0eparameter_json\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"B\n\x08TaskType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x1c\n\x18\x46\x45TCH_LAST_BUILD_DETAILS\x10\x01\x12\x0b\n\x07RUN_JOB\x10\x02\x42\x06\n\x04taskb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.playbooks.source_task_definitions.jenkins_task_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JENKINS._serialized_start=144
  _JENKINS._serialized_end=638
  _JENKINS_LASTBUILDDETAILS._serialized_start=338
  _JENKINS_LASTBUILDDETAILS._serialized_end=404
  _JENKINS_RUNJOB._serialized_start=407
  _JENKINS_RUNJOB._serialized_end=562
  _JENKINS_TASKTYPE._serialized_start=564
  _JENKINS_TASKTYPE._serialized_end=630
# @@protoc_insertion_point(module_scope)
