# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/playbooks/source_task_definitions/lambda_function_task.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protos/playbooks/source_task_definitions/lambda_function_task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCprotos/playbooks/source_task_definitions/lambda_function_task.proto\x12\x10protos.playbooks\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x9c\x02\n\x06Lambda\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.protos.playbooks.Lambda.TaskType\x12\x35\n\x08\x66unction\x18\x03 \x01(\x0b\x32!.protos.playbooks.Lambda.FunctionH\x00\x1a{\n\x08\x46unction\x12\x30\n\ndefinition\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x14\n\x0crequirements\x18\x02 \x03(\t\x12\'\n\x06inputs\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"%\n\x08TaskType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08\x46UNCTION\x10\x01\x42\x06\n\x04taskb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.playbooks.source_task_definitions.lambda_function_task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LAMBDA']._serialized_start=152
  _globals['_LAMBDA']._serialized_end=436
  _globals['_LAMBDA_FUNCTION']._serialized_start=266
  _globals['_LAMBDA_FUNCTION']._serialized_end=389
  _globals['_LAMBDA_TASKTYPE']._serialized_start=391
  _globals['_LAMBDA_TASKTYPE']._serialized_end=428
# @@protoc_insertion_point(module_scope)
