# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/playbooks/source_task_definitions/mongodb_task.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;protos/playbooks/source_task_definitions/mongodb_task.proto\x12\x10protos.playbooks\x1a\x1egoogle/protobuf/wrappers.proto\"\x8c\x04\n\x07MongoDB\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".protos.playbooks.MongoDB.TaskType\x12:\n\ndata_fetch\x18\x02 \x01(\x0b\x32$.protos.playbooks.MongoDB.MongoQueryH\x00\x1a\xe1\x02\n\nMongoQuery\x12.\n\x08\x64\x61tabase\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x30\n\ncollection\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x34\n\x0eorder_by_field\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12+\n\x05limit\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12-\n\x07\x66ilters\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x30\n\nprojection\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12-\n\x07timeout\x18\x07 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\"\'\n\x08TaskType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nDATA_FETCH\x10\x01\x42\x06\n\x04taskb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.playbooks.source_task_definitions.mongodb_task_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MONGODB._serialized_start=114
  _MONGODB._serialized_end=638
  _MONGODB_MONGOQUERY._serialized_start=236
  _MONGODB_MONGOQUERY._serialized_end=589
  _MONGODB_TASKTYPE._serialized_start=591
  _MONGODB_TASKTYPE._serialized_end=630
# @@protoc_insertion_point(module_scope)
