# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/playbooks/source_task_definitions/posthog_task.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;protos/playbooks/source_task_definitions/posthog_task.proto\x12\x10protos.playbooks\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xed\x01\n\x07PostHog\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".protos.playbooks.PostHog.TaskType\x12?\n\x0bhogql_query\x18\x02 \x01(\x0b\x32(.protos.playbooks.PostHog.HogQLQueryTaskH\x00\x1a=\n\x0eHogQLQueryTask\x12+\n\x05query\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"(\n\x08TaskType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0bHOGQL_QUERY\x10\x01\x42\x06\n\x04taskb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.playbooks.source_task_definitions.posthog_task_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSTHOG._serialized_start=144
  _POSTHOG._serialized_end=381
  _POSTHOG_HOGQLQUERYTASK._serialized_start=270
  _POSTHOG_HOGQLQUERYTASK._serialized_end=331
  _POSTHOG_TASKTYPE._serialized_start=333
  _POSTHOG_TASKTYPE._serialized_end=373
# @@protoc_insertion_point(module_scope)
